"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional


@dataclasses.dataclass
class SchemeOauth2:
    
    authorization: str = dataclasses.field(metadata={'security': { 'field_name': 'Authorization' }})  
    

@dataclasses.dataclass
class SchemePersonalAccessToken:
    
    authorization: str = dataclasses.field(metadata={'security': { 'field_name': 'Authorization' }})  
    

@dataclasses.dataclass
class Security:
    
    oauth2: Optional[SchemeOauth2] = dataclasses.field(default=None, metadata={'security': { 'scheme': True, 'type': 'oauth2' }})  
    personal_access_token: Optional[SchemePersonalAccessToken] = dataclasses.field(default=None, metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer' }})  
    