"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from sdk import utils

class SubmissionExternalURLResultTypeEnum(str, Enum):
    r"""Indicates that the routing form submission resulted in a redirect to an external URL."""
    EXTERNAL_URL = 'external_url'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SubmissionExternalURLResult:
    r"""Information about the external URL Routing Form Submission result."""
    
    type: SubmissionExternalURLResultTypeEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""Indicates that the routing form submission resulted in a redirect to an external URL."""  
    value: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('value') }})
    r"""The external URL the respondent were redirected to."""  
    