"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import cancellation as shared_cancellation
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from sdk import utils
from typing import Optional


@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationPathParams:
    
    uuid: str = dataclasses.field(metadata={'path_param': { 'field_name': 'uuid', 'style': 'simple', 'explode': False }})
    r"""The event's unique indentifier"""  
    

@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRawRequest:
    
    path_params: PostScheduledEventsUUIDCancellationPathParams = dataclasses.field()  
    request: Optional[bytes] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/xml' }})
    r"""Optional cancellation reason."""  
    
class PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum(str, Enum):
    YOU_ARE_NOT_ALLOWED_TO_CANCEL_THIS_EVENT = "You are not allowed to cancel this event"
    EVENT_IN_THE_PAST = "Event in the past"
    EVENT_IS_ALREADY_CANCELED = "Event is already canceled"

class PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum(str, Enum):
    PERMISSION_DENIED = "Permission Denied"


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRaw403ApplicationJSON:
    r"""Caller not authorized to perform this action"""
    
    message: Optional[PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})  
    title: Optional[PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title'), 'exclude': lambda f: f is None }})  
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRawErrorResponseDetails:
    
    message: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message') }})  
    parameter: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('parameter'), 'exclude': lambda f: f is None }})  
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRawErrorResponse:
    r"""Error Object"""
    
    message: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message') }})  
    title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title') }})  
    details: Optional[list[PostScheduledEventsUUIDCancellationRawErrorResponseDetails]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('details'), 'exclude': lambda f: f is None }})  
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRaw201ApplicationJSON:
    r"""Created"""
    
    resource: shared_cancellation.Cancellation = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resource') }})
    r"""Provides data pertaining to the cancellation of the Event"""  
    

@dataclasses.dataclass
class PostScheduledEventsUUIDCancellationRawResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    error_response: Optional[PostScheduledEventsUUIDCancellationRawErrorResponse] = dataclasses.field(default=None)
    r"""Request is not valid"""  
    post_scheduled_events_uuid_cancellation_raw_201_application_json_object: Optional[PostScheduledEventsUUIDCancellationRaw201ApplicationJSON] = dataclasses.field(default=None)
    r"""Created"""  
    post_scheduled_events_uuid_cancellation_raw_403_application_json_object: Optional[PostScheduledEventsUUIDCancellationRaw403ApplicationJSON] = dataclasses.field(default=None)
    r"""Caller not authorized to perform this action"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    